# Generated by Django 5.2.7 on 2025-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_maininfos_maininfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
    ]
