# Generated by Django 5.2.7 on 2025-10-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sociallink_icon_sociallink_total_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
