# Generated by Django 5.2.7 on 2025-10-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_introourcompany_mainfeature_mainslider_ourservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introourcompany',
            name='list1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
