# Generated by Django 5.2.7 on 2025-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_introourcompany_list1_introourcompany_list2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfeature',
            name='background_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='background_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
