# Generated by Django 5.2.7 on 2025-10-22 05:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mainfeature_background_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('benefit1', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit1_text', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit1_quality1', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit1_quality2', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit1_quality3', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit1_quality4', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit2', models.CharField(blank=True, max_length=200, null=True)),
                ('benefit2_text', models.CharField(blank=True, max_length=200, null=True)),
                ('client_count', models.IntegerField(default=0)),
                ('client_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('project_number', models.IntegerField(default=0)),
                ('project_content', models.CharField(blank=True, max_length=200, null=True)),
                ('costumer_number', models.IntegerField(default=0)),
                ('costumer_content', models.CharField(blank=True, max_length=200, null=True)),
                ('button_name', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('button_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('rate', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
