# Generated by Django 5.2.7 on 2025-10-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ourblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourblog',
            name='description',
        ),
    ]
