# Generated by Django 5.2.7 on 2025-10-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_ourblog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainfeature',
            name='background_image1',
        ),
        migrations.RemoveField(
            model_name='mainfeature',
            name='background_image2',
        ),
    ]
