# Generated by Django 5.2.7 on 2025-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_mainfeature_background_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourfact',
            old_name='costumer_content',
            new_name='customer_content',
        ),
        migrations.RemoveField(
            model_name='ourfact',
            name='costumer_number',
        ),
        migrations.RemoveField(
            model_name='ourfact',
            name='icon',
        ),
        migrations.AddField(
            model_name='ourfact',
            name='customer_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
