# Generated by Django 5.2.7 on 2025-10-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_ourexpert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourexpert',
            old_name='linkedin_url',
            new_name='telegram_url',
        ),
    ]
