# Generated by Django 5.2.7 on 2025-10-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_linkedin_url_ourexpert_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourexpert',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
