# Generated by Django 5.2.7 on 2025-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
