# Generated by Django 5.2.7 on 2025-10-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_contactmessage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
