# Generated by Django 5.2.7 on 2025-10-23 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ourservice_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
