# Generated by Django 5.2.7 on 2025-10-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
