# Generated by Django 5.2.7 on 2025-10-24 10:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_ourproject_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mini_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('specifications', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_top', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, to='home.productimage')),
            ],
        ),
    ]
