# Generated by Django 5.2.7 on 2025-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
