# Generated by Django 5.2.7 on 2025-10-28 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_category_remove_ourblog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourblog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category'),
        ),
    ]
