# Generated by Django 5.2.7 on 2025-11-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_ourblog_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Savatcha', 'verbose_name_plural': 'Savatchalar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Aloqa Xabari', 'verbose_name_plural': 'Aloqa Xabarlari'},
        ),
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'Email Tasdiqlash Tokeni', 'verbose_name_plural': 'Email Tasdiqlash Tokenlari'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': "Tez-Tez So'raladigan Savol", 'verbose_name_plural': "Tez-Tez So'raladigan Savollar"},
        ),
        migrations.AlterModelOptions(
            name='introourcompany',
            options={'verbose_name': 'Kompaniya Haqida', 'verbose_name_plural': 'Kompaniya Haqida'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Yoqtirish', 'verbose_name_plural': 'Yoqtirishlar'},
        ),
        migrations.AlterModelOptions(
            name='mainfeature',
            options={'verbose_name': 'Asosiy Xususiyat', 'verbose_name_plural': 'Asosiy Xususiyatlar'},
        ),
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': "Asosiy Ma'lumot", 'verbose_name_plural': "Asosiy Ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'verbose_name': 'Asosiy Slayder', 'verbose_name_plural': 'Asosiy Slayderlar'},
        ),
        migrations.AlterModelOptions(
            name='ourbenefit',
            options={'verbose_name': 'Bizning Afzallik', 'verbose_name_plural': 'Bizning Afzalliklar'},
        ),
        migrations.AlterModelOptions(
            name='ourblog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Bloglar'},
        ),
        migrations.AlterModelOptions(
            name='ourexpert',
            options={'verbose_name': 'Bizning Mutaxassis', 'verbose_name_plural': 'Bizning Mutaxassislar'},
        ),
        migrations.AlterModelOptions(
            name='ourfact',
            options={'verbose_name': 'Bizning Statistika', 'verbose_name_plural': 'Bizning Statistikalar'},
        ),
        migrations.AlterModelOptions(
            name='ourproject',
            options={'verbose_name': 'Bizning Loyiha', 'verbose_name_plural': 'Bizning Loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='ourservice',
            options={'verbose_name': 'Bizning Xizmat', 'verbose_name_plural': 'Bizning Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='ourtestimonial',
            options={'verbose_name': 'Mijoz Sharhi', 'verbose_name_plural': 'Mijoz Sharhlari'},
        ),
        migrations.AlterModelOptions(
            name='ourworkprocess',
            options={'verbose_name': 'Ish Jarayoni', 'verbose_name_plural': 'Ish Jarayonlari'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Parol Tiklash Tokeni', 'verbose_name_plural': 'Parol Tiklash Tokenlari'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Mahsulot Rasmi', 'verbose_name_plural': 'Mahsulot Rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Ijtimoiy Tarmoq', 'verbose_name_plural': 'Ijtimoiy Tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='teamapplication',
            options={'verbose_name': 'Jamoaga Ariza', 'verbose_name_plural': 'Jamoaga Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Foydalanuvchi Profili', 'verbose_name_plural': 'Foydalanuvchi Profillari'},
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='button_1_url',
        ),
        migrations.RemoveField(
            model_name='mainslider',
            name='button_2_url',
        ),
    ]
