# Generated by Django 5.2.7 on 2025-11-05 08:23

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_cart_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xizmat'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Muddati tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Ishlatilganmi'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='user_data',
            field=models.JSONField(verbose_name="Foydalanuvchi ma'lumotlari"),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='verification_code',
            field=models.CharField(max_length=6, verbose_name='Tasdiqlash kodi'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='button_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='button_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Tajriba yillari'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='icon1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-ikonka'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='icon2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2-ikonka'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='icon_text1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-ikonka matni'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='icon_text2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-ikonka matni'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='1-rasm'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='2-rasm'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='list1',
            field=models.TextField(blank=True, null=True, verbose_name="1-ro'yxat"),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='list2',
            field=models.TextField(blank=True, null=True, verbose_name="2-ro'yxat"),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='list3',
            field=models.TextField(blank=True, null=True, verbose_name="3-ro'yxat"),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='introourcompany',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Aloqa email'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='footer_text',
            field=models.TextField(verbose_name='Footer matni'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='Sayt nomi'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='button_1_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-tugma nomi'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='button_2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2-tugma nomi'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit1_quality1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 1'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit1_quality2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 2'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit1_quality3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 3'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit1_quality4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 4'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit1_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik matni'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='benefit2_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik matni'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='client_count',
            field=models.IntegerField(default=0, verbose_name='Mijozlar soni'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='client_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz matni'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourbenefit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='minititle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mini sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nashr sanasi'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourblog',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourexpert',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='button_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='button_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='button_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='customer_content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz mazmuni'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='customer_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mijozlar soni'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='project_content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha mazmuni'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='project_number',
            field=models.IntegerField(default=0, verbose_name='Loyihalar soni'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourfact',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='button_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='TOP loyihami'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name='Loyiha sanasi'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='project_link',
            field=models.URLField(blank=True, null=True, verbose_name='Loyiha havolasi'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='TOP xizmatmi'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='pagename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='rate',
            field=models.IntegerField(default=5, verbose_name='Baho'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourtestimonial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='page_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sahifa matni'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='pagename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='step_number',
            field=models.IntegerField(verbose_name='Qadam raqami'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='ourworkprocess',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Muddati tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Ishlatilganmi'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='verification_code',
            field=models.CharField(max_length=6, verbose_name='Tasdiqlash kodi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='home.productimage', verbose_name='Rasmlar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='TOP mahsulotmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_description',
            field=models.TextField(verbose_name='Qisqacha tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Eski narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texnik xususiyatlari'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Available', max_length=50, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(max_length=100, verbose_name='Platforma'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='total_followers',
            field=models.IntegerField(default=0, verbose_name='Obunachi soni'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='teamapplication',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
