# Generated by Django 5.2.7 on 2025-11-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_cart_created_at_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourfact',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tugma havolasi'),
        ),
    ]
