# Generated by Django 5.2.7 on 2025-11-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_ourfact_button_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourblog',
            name='url',
        ),
    ]
