# Generated by Django 5.2.7 on 2025-11-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_ourblog_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='url',
        ),
    ]
