# Generated by Django 5.2.8 on 2025-11-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='telegram_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram xabar ID'),
        ),
    ]
