# Generated by Django 5.2.8 on 2025-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_chatmessage_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
