# Generated by Django 5.2.8 on 2025-12-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_chatsession_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Xizmat Kategoriyasi',
                'verbose_name_plural': 'Xizmat Kategoriyalari',
            },
        ),
        migrations.AddField(
            model_name='ourservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.servicecategory', verbose_name='Kategoriyasi'),
        ),
    ]
