# Generated by Django 5.2.8 on 2025-12-03 04:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_servicecategory_ourservice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='pagename',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
