# Generated by Django 5.2.8 on 2025-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_ourservice_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='category',
        ),
        migrations.AddField(
            model_name='ourservice',
            name='category',
            field=models.ManyToManyField(blank=True, to='home.servicecategory', verbose_name='Kategoriyasi'),
        ),
    ]
