# Generated by Django 5.2.7 on 2025-12-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_ourservice_category_ourservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='pagename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
    ]
