# Generated by Django 5.2.7 on 2025-12-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_ourservice_pagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ikonka'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Rasm'),
        ),
    ]
