# Generated by Django 5.2.7 on 2025-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_ourservice_description_ourservice_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='image',
        ),
        migrations.AddField(
            model_name='ourservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
