# Generated by Django 5.2.7 on 2025-12-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_ourservice_description_remove_ourservice_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
