# Generated by Django 5.2.8 on 2025-12-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_populate_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='image',
        ),
    ]
