# Generated by Django 5.2.7 on 2025-12-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_ourservice_slug_alter_servicecategory_slug'),
        ('home', '0047_populate_slugs'),
    ]

    operations = [
    ]
