# Generated by Django 6.0 on 2025-12-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_merge_20251203_1332'),
        ('home', '0048_remove_ourservice_description_remove_ourservice_icon_and_more'),
    ]

    operations = [
    ]
