# Generated by Django 6.0 on 2025-12-10 14:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_ourservice_description_remove_ourservice_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='button_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='button_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='button_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='icon_text1_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-ikonka matni'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='icon_text1_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-ikonka matni'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='icon_text1_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-ikonka matni'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='icon_text2_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-ikonka matni'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='icon_text2_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-ikonka matni'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='icon_text2_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-ikonka matni'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list1_en',
            field=models.TextField(blank=True, null=True, verbose_name="1-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list1_ru',
            field=models.TextField(blank=True, null=True, verbose_name="1-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list1_uz',
            field=models.TextField(blank=True, null=True, verbose_name="1-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list2_en',
            field=models.TextField(blank=True, null=True, verbose_name="2-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list2_ru',
            field=models.TextField(blank=True, null=True, verbose_name="2-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list2_uz',
            field=models.TextField(blank=True, null=True, verbose_name="2-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list3_en',
            field=models.TextField(blank=True, null=True, verbose_name="3-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list3_ru',
            field=models.TextField(blank=True, null=True, verbose_name="3-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='list3_uz',
            field=models.TextField(blank=True, null=True, verbose_name="3-ro'yxat"),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='introourcompany',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainfeature',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='address_uz',
            field=models.TextField(null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='footer_text_en',
            field=models.TextField(null=True, verbose_name='Footer matni'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='footer_text_ru',
            field=models.TextField(null=True, verbose_name='Footer matni'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='footer_text_uz',
            field=models.TextField(null=True, verbose_name='Footer matni'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='opening_hours_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='opening_hours_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='opening_hours_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ish vaqti'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='site_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='site_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='site_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_1_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-tugma nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_1_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-tugma nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_1_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-tugma nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_2_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2-tugma nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_2_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2-tugma nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='button_2_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2-tugma nomi'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality1_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 1'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality1_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 1'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality1_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 1'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality2_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 2'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality2_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 2'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality2_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 2'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality3_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 3'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality3_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 3'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality3_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 3'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality4_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 4'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality4_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 4'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_quality4_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1-afzallik xususiyati 4'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit1_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1-afzallik'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit2_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit2_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit2_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit2_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit2_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='benefit2_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2-afzallik'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='client_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='client_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='client_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz matni'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourbenefit',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='author_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='author_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='author_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='minititle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mini sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='minititle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mini sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='minititle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mini sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourblog',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='position_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourexpert',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='button_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='button_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='button_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='button_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='button_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='customer_content_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz mazmuni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='customer_content_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz mazmuni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='customer_content_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mijoz mazmuni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='project_content_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha mazmuni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='project_content_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha mazmuni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='project_content_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha mazmuni'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourfact',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='button_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='button_name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='button_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tugma nomi'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='category_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mazmun'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='project_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='project_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='project_name_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='pagename_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='pagename_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='pagename_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourservice',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='feedback_en',
            field=models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='feedback_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='feedback_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='position_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourtestimonial',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='page_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sahifa matni'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='page_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sahifa matni'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='page_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sahifa matni'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='pagename_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='pagename_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='pagename_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sahifa nomi'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='ourworkprocess',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='mini_description_en',
            field=models.TextField(null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='mini_description_ru',
            field=models.TextField(null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='mini_description_uz',
            field=models.TextField(null=True, verbose_name='Qisqacha tavsif'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texnik xususiyatlari'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texnik xususiyatlari'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texnik xususiyatlari'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_en',
            field=models.CharField(default='Available', max_length=50, null=True, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_ru',
            field=models.CharField(default='Available', max_length=50, null=True, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_uz',
            field=models.CharField(default='Available', max_length=50, null=True, verbose_name='Holati'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='platform_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Platforma'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='platform_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Platforma'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='platform_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Platforma'),
        ),
    ]
